options:

  auto-update: true


waila:

  # If set to true, will disable waila for all players,
  # overriding individual preferences and 'disabled-in'
  disabled: false

  # List of worlds that the WAILA is disabled in
  disabled-in: []

  # Can be 'bossbar' or 'hotbar'
  location: bossbar

  # Whether or not to keep colors and format of the text. If set to false, defaults to white.
  use-original-colors: true

  # The color of the bossbar. Must be a valid color in 'snake_case'.
  # 'inherit' means 'match the color of the bossbar to that of the text'.
  # 'default' is white
  bossbar-color: inherit

  # cargo/energy-size is the size of the network,
  # cargo-channel only applies to input/output nodes, and energy-stored
  # only applies to machines with an energy buffer
  show-cargo-size: true
  show-cargo-channel: true
  show-energy-size: true
  show-energy-stored: true

  # Rate at which WAILA updates, in *game* ticks
  tick-rate: 10