name: SlimeHUD

author: SchnTgaiSpock

description: A utility addon that adds a toggleable WAILA (What Am I Looking At) HUD for placed Slimefun items.

main: io.github.schntgaispock.slimehud.SlimeHUD

website: https://github.com/SchnTgaiSpock/SlimeHUD

version: ${project.version}

folia-supported: true

api-version: 1.14

depend:
- Slimefun
- GuizhanLibPlugin

softdepend:
- PlaceholderAPI
- SlimefunTranslation

commands:
  slimehud:
    description: /slimehud
    aliases: [sfhud, sfh]
    usage: Press [tab] for usage hints

permissions:
  slimehud.togglewaila:
    description: Able to toggle the WAILA HUD
    default: true